In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/iris1.csv')

In [5]:
df.head()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width        Class
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa
4           5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Sepal_Length   150 non-null    float64
 1    Sepal_Width   150 non-null    float64
 2    Petal_Length  150 non-null    float64
 3    Petal_Width   150 non-null    float64
 4   Class          150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


The dataset tells us the features of different classes of iris. Here class is our target variables. We can see that all features influence the target.

Preprocessing is required as we need to convert the class of iris into numeric type using label encoding

In [7]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df.iloc[:,4]=le.fit_transform(df.iloc[:,4])

In [8]:
df.head()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width  Class
0           5.1           3.5            1.4           0.2      0
1           4.9           3.0            1.4           0.2      0
2           4.7           3.2            1.3           0.2      0
3           4.6           3.1            1.5           0.2      0
4           5.0           3.6            1.4           0.2      0

In [9]:
x=df.drop('Class',axis=1)
y=df[['Class']]

New point

In [10]:
test=[5,2.5,3,1.8]

train test split

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=5)

In [12]:
from sklearn.naive_bayes import MultinomialNB
multinb= MultinomialNB()
model= multinb.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
y.value_counts()

Class
0        50
1        50
2        50
dtype: int64

We can see that the dataset is perfectly balanced

In [14]:
y_pred=model.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[12  0  0]
 [ 0  9  5]
 [ 0  0 12]]


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.64      1.00      0.78         9
           2       1.00      0.71      0.83        17

    accuracy                           0.87        38
   macro avg       0.88      0.90      0.87        38
weighted avg       0.92      0.87      0.87        38



In [18]:
print(model.predict([test]))

[2]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


Final Inference : Multinomial Naive Bayes algorithm is a probabilistic learning method. The algorithm is based on the Bayes theorem and predicts the target. Multinomial NB cares about counts for multiple features that do occur. 